/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   spring_message__headers_entry__init
                     (SpringMessage__HeadersEntry         *message)
{
  static const SpringMessage__HeadersEntry init_value = SPRING_MESSAGE__HEADERS_ENTRY__INIT;
  *message = init_value;
}
void   spring_message__init
                     (SpringMessage         *message)
{
  static const SpringMessage init_value = SPRING_MESSAGE__INIT;
  *message = init_value;
}
size_t spring_message__get_packed_size
                     (const SpringMessage *message)
{
  assert(message->base.descriptor == &spring_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spring_message__pack
                     (const SpringMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spring_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spring_message__pack_to_buffer
                     (const SpringMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spring_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SpringMessage *
       spring_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SpringMessage *)
     protobuf_c_message_unpack (&spring_message__descriptor,
                                allocator, len, data);
}
void   spring_message__free_unpacked
                     (SpringMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spring_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor spring_message__headers_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SpringMessage__HeadersEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SpringMessage__HeadersEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spring_message__headers_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange spring_message__headers_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor spring_message__headers_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SpringMessage.HeadersEntry",
  "HeadersEntry",
  "SpringMessage__HeadersEntry",
  "",
  sizeof(SpringMessage__HeadersEntry),
  2,
  spring_message__headers_entry__field_descriptors,
  spring_message__headers_entry__field_indices_by_name,
  1,  spring_message__headers_entry__number_ranges,
  (ProtobufCMessageInit) spring_message__headers_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spring_message__field_descriptors[2] =
{
  {
    "payload",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SpringMessage, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "headers",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SpringMessage, n_headers),
    offsetof(SpringMessage, headers),
    &spring_message__headers_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spring_message__field_indices_by_name[] = {
  1,   /* field[1] = headers */
  0,   /* field[0] = payload */
};
static const ProtobufCIntRange spring_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor spring_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SpringMessage",
  "SpringMessage",
  "SpringMessage",
  "",
  sizeof(SpringMessage),
  2,
  spring_message__field_descriptors,
  spring_message__field_indices_by_name,
  1,  spring_message__number_ranges,
  (ProtobufCMessageInit) spring_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
