spring:
  cloud:
    gateway:
      routes:
        - uri: https://github.com
          predicates:
            - Path=/github/**
            - CustomWASMPredicate=message.wasm
          filters:
            - StripPrefix=1
        - uri: https://httpbin.org
          predicates:
            - Path=/response/**
          filters:
            - CustomWASMResponseFilter
            - StripPrefix=1
        - uri: https://httpbin.org
          predicates:
            - Path=/request/**
          filters:
            - CustomWASMRequestFilter
            - StripPrefix=1