/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: generic.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "generic.pb-c.h"
void   generic_message__fields_entry__init
                     (GenericMessage__FieldsEntry         *message)
{
  static const GenericMessage__FieldsEntry init_value = GENERIC_MESSAGE__FIELDS_ENTRY__INIT;
  *message = init_value;
}
void   generic_message__init
                     (GenericMessage         *message)
{
  static const GenericMessage init_value = GENERIC_MESSAGE__INIT;
  *message = init_value;
}
size_t generic_message__get_packed_size
                     (const GenericMessage *message)
{
  assert(message->base.descriptor == &generic_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t generic_message__pack
                     (const GenericMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &generic_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t generic_message__pack_to_buffer
                     (const GenericMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &generic_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GenericMessage *
       generic_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GenericMessage *)
     protobuf_c_message_unpack (&generic_message__descriptor,
                                allocator, len, data);
}
void   generic_message__free_unpacked
                     (GenericMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &generic_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   generic_list__init
                     (GenericList         *message)
{
  static const GenericList init_value = GENERIC_LIST__INIT;
  *message = init_value;
}
size_t generic_list__get_packed_size
                     (const GenericList *message)
{
  assert(message->base.descriptor == &generic_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t generic_list__pack
                     (const GenericList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &generic_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t generic_list__pack_to_buffer
                     (const GenericList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &generic_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GenericList *
       generic_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GenericList *)
     protobuf_c_message_unpack (&generic_list__descriptor,
                                allocator, len, data);
}
void   generic_list__free_unpacked
                     (GenericList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &generic_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   generic_value__init
                     (GenericValue         *message)
{
  static const GenericValue init_value = GENERIC_VALUE__INIT;
  *message = init_value;
}
size_t generic_value__get_packed_size
                     (const GenericValue *message)
{
  assert(message->base.descriptor == &generic_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t generic_value__pack
                     (const GenericValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &generic_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t generic_value__pack_to_buffer
                     (const GenericValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &generic_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GenericValue *
       generic_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GenericValue *)
     protobuf_c_message_unpack (&generic_value__descriptor,
                                allocator, len, data);
}
void   generic_value__free_unpacked
                     (GenericValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &generic_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor generic_message__fields_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GenericMessage__FieldsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GenericMessage__FieldsEntry, value),
    &generic_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned generic_message__fields_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange generic_message__fields_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor generic_message__fields_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GenericMessage.FieldsEntry",
  "FieldsEntry",
  "GenericMessage__FieldsEntry",
  "",
  sizeof(GenericMessage__FieldsEntry),
  2,
  generic_message__fields_entry__field_descriptors,
  generic_message__fields_entry__field_indices_by_name,
  1,  generic_message__fields_entry__number_ranges,
  (ProtobufCMessageInit) generic_message__fields_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor generic_message__field_descriptors[1] =
{
  {
    "fields",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, n_fields),
    offsetof(GenericMessage, fields),
    &generic_message__fields_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned generic_message__field_indices_by_name[] = {
  0,   /* field[0] = fields */
};
static const ProtobufCIntRange generic_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor generic_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GenericMessage",
  "GenericMessage",
  "GenericMessage",
  "",
  sizeof(GenericMessage),
  1,
  generic_message__field_descriptors,
  generic_message__field_indices_by_name,
  1,  generic_message__number_ranges,
  (ProtobufCMessageInit) generic_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor generic_list__field_descriptors[1] =
{
  {
    "values",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericList, n_values),
    offsetof(GenericList, values),
    &generic_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned generic_list__field_indices_by_name[] = {
  0,   /* field[0] = values */
};
static const ProtobufCIntRange generic_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor generic_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GenericList",
  "GenericList",
  "GenericList",
  "",
  sizeof(GenericList),
  1,
  generic_list__field_descriptors,
  generic_list__field_indices_by_name,
  1,  generic_list__number_ranges,
  (ProtobufCMessageInit) generic_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor generic_value__field_descriptors[10] =
{
  {
    "null_val",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(GenericValue, value_case),
    offsetof(GenericValue, null_val),
    &google__protobuf__null_value__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_val",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(GenericValue, value_case),
    offsetof(GenericValue, double_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_val",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(GenericValue, value_case),
    offsetof(GenericValue, string_val),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_val",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(GenericValue, value_case),
    offsetof(GenericValue, bool_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_val",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericValue, value_case),
    offsetof(GenericValue, message_val),
    &generic_message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list_val",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericValue, value_case),
    offsetof(GenericValue, list_val),
    &generic_list__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes_val",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(GenericValue, value_case),
    offsetof(GenericValue, bytes_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_val",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(GenericValue, value_case),
    offsetof(GenericValue, float_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_val",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    offsetof(GenericValue, value_case),
    offsetof(GenericValue, int_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long_val",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    offsetof(GenericValue, value_case),
    offsetof(GenericValue, long_val),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned generic_value__field_indices_by_name[] = {
  3,   /* field[3] = bool_val */
  6,   /* field[6] = bytes_val */
  1,   /* field[1] = double_val */
  7,   /* field[7] = float_val */
  8,   /* field[8] = int_val */
  5,   /* field[5] = list_val */
  9,   /* field[9] = long_val */
  4,   /* field[4] = message_val */
  0,   /* field[0] = null_val */
  2,   /* field[2] = string_val */
};
static const ProtobufCIntRange generic_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor generic_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GenericValue",
  "GenericValue",
  "GenericValue",
  "",
  sizeof(GenericValue),
  10,
  generic_value__field_descriptors,
  generic_value__field_indices_by_name,
  1,  generic_value__number_ranges,
  (ProtobufCMessageInit) generic_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
