/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: generic.proto */

#ifndef PROTOBUF_C_generic_2eproto__INCLUDED
#define PROTOBUF_C_generic_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/struct.pb-c.h"

typedef struct _GenericMessage GenericMessage;
typedef struct _GenericMessage__FieldsEntry GenericMessage__FieldsEntry;
typedef struct _GenericList GenericList;
typedef struct _GenericValue GenericValue;


/* --- enums --- */


/* --- messages --- */

struct  _GenericMessage__FieldsEntry
{
  ProtobufCMessage base;
  char *key;
  GenericValue *value;
};
#define GENERIC_MESSAGE__FIELDS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&generic_message__fields_entry__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


struct  _GenericMessage
{
  ProtobufCMessage base;
  size_t n_fields;
  GenericMessage__FieldsEntry **fields;
};
#define GENERIC_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&generic_message__descriptor) \
    , 0,NULL }


struct  _GenericList
{
  ProtobufCMessage base;
  size_t n_values;
  GenericValue **values;
};
#define GENERIC_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&generic_list__descriptor) \
    , 0,NULL }


typedef enum {
  GENERIC_VALUE__VALUE__NOT_SET = 0,
  GENERIC_VALUE__VALUE_NULL_VAL = 1,
  GENERIC_VALUE__VALUE_DOUBLE_VAL = 2,
  GENERIC_VALUE__VALUE_STRING_VAL = 3,
  GENERIC_VALUE__VALUE_BOOL_VAL = 4,
  GENERIC_VALUE__VALUE_MESSAGE_VAL = 5,
  GENERIC_VALUE__VALUE_LIST_VAL = 6,
  GENERIC_VALUE__VALUE_BYTES_VAL = 7,
  GENERIC_VALUE__VALUE_FLOAT_VAL = 8,
  GENERIC_VALUE__VALUE_INT_VAL = 9,
  GENERIC_VALUE__VALUE_LONG_VAL = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GENERIC_VALUE__VALUE)
} GenericValue__ValueCase;

struct  _GenericValue
{
  ProtobufCMessage base;
  GenericValue__ValueCase value_case;
  union {
    Google__Protobuf__NullValue null_val;
    double double_val;
    char *string_val;
    protobuf_c_boolean bool_val;
    GenericMessage *message_val;
    GenericList *list_val;
    ProtobufCBinaryData bytes_val;
    float float_val;
    int32_t int_val;
    int64_t long_val;
  };
};
#define GENERIC_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&generic_value__descriptor) \
    , GENERIC_VALUE__VALUE__NOT_SET, {0} }


/* GenericMessage__FieldsEntry methods */
void   generic_message__fields_entry__init
                     (GenericMessage__FieldsEntry         *message);
/* GenericMessage methods */
void   generic_message__init
                     (GenericMessage         *message);
size_t generic_message__get_packed_size
                     (const GenericMessage   *message);
size_t generic_message__pack
                     (const GenericMessage   *message,
                      uint8_t             *out);
size_t generic_message__pack_to_buffer
                     (const GenericMessage   *message,
                      ProtobufCBuffer     *buffer);
GenericMessage *
       generic_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   generic_message__free_unpacked
                     (GenericMessage *message,
                      ProtobufCAllocator *allocator);
/* GenericList methods */
void   generic_list__init
                     (GenericList         *message);
size_t generic_list__get_packed_size
                     (const GenericList   *message);
size_t generic_list__pack
                     (const GenericList   *message,
                      uint8_t             *out);
size_t generic_list__pack_to_buffer
                     (const GenericList   *message,
                      ProtobufCBuffer     *buffer);
GenericList *
       generic_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   generic_list__free_unpacked
                     (GenericList *message,
                      ProtobufCAllocator *allocator);
/* GenericValue methods */
void   generic_value__init
                     (GenericValue         *message);
size_t generic_value__get_packed_size
                     (const GenericValue   *message);
size_t generic_value__pack
                     (const GenericValue   *message,
                      uint8_t             *out);
size_t generic_value__pack_to_buffer
                     (const GenericValue   *message,
                      ProtobufCBuffer     *buffer);
GenericValue *
       generic_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   generic_value__free_unpacked
                     (GenericValue *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*GenericMessage__FieldsEntry_Closure)
                 (const GenericMessage__FieldsEntry *message,
                  void *closure_data);
typedef void (*GenericMessage_Closure)
                 (const GenericMessage *message,
                  void *closure_data);
typedef void (*GenericList_Closure)
                 (const GenericList *message,
                  void *closure_data);
typedef void (*GenericValue_Closure)
                 (const GenericValue *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor generic_message__descriptor;
extern const ProtobufCMessageDescriptor generic_message__fields_entry__descriptor;
extern const ProtobufCMessageDescriptor generic_list__descriptor;
extern const ProtobufCMessageDescriptor generic_value__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_generic_2eproto__INCLUDED */
